---
title: "MID/CMB, Radcliffe, Kilteasheen, Iberian Medieval, calculus MetaPhlAn3 beta diversity PC-metadata correlations"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---


```{r load_libraries, echo = F, message = F}
library(knitr)
library(data.table)
library(mixOmics)
library(variancePartition)
library(janitor)
library(pander)
library(tidyverse)
library(viridis)
library(cowplot)
library(RColorBrewer)
opts_chunk$set(echo=F, warning=F, message=F, dpi=150)
```

Set the working directory of the notebook to the parent directory of the 
notebook itself.  

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

# MetaPhlAn3

```{r load_data}
# read in the species table
mpa3_raw <- fread("./05-results.backup/mpa3_abundance_table.tsv") %>%
  select(-NCBI_tax_id)

# clean the file names
colnames(mpa3_raw) <- gsub(".metaphlan3","", colnames(mpa3_raw))
colnames(mpa3_raw) <- gsub(".SG1","", colnames(mpa3_raw))

# filter to have only species
mpa3_sp <- mpa3_raw %>% 
  filter(str_detect(clade_name, "s__")) %>%
  separate(clade_name, into = c("K","P","C","O","F","G","Species"), sep = "\\|") %>%
  select(-c("K","P","C","O","F","G")) %>%
  mutate(Species = str_replace_all(Species, "s__",""),
         Species = str_replace_all(Species, "_"," ")) %>%
  # these samples have no metadata
  select(-c("MID025.A0101","MID033.A0101","MID052.A0101","MID056.A0101","MID065.A0101","MID068.A0101","MID076.A0101","MID078.A0101")) %>%
  arrange(Species)

```


Now decontam the tables
```{r}
mpa3_contaminants <- fread("./05-results.backup/contaminant_species_mid_mpa3.tsv", sep = "\t") %>%
  bind_rows(., fread("./05-results.backup/contaminant_species_kilteasheen_mpa3.tsv", sep = "\t")) %>%
  bind_rows(., fread("./05-results.backup/contaminant_species_iberia_mpa3.tsv", sep = "\t")) %>%
  unique()

# remove contaminant species from nt table
mpa3_species_decontam <- mpa3_sp %>%
  anti_join(., mpa3_contaminants)

```

```{r outliers}
outliers_mpa3 <- c("EXB059.A2101","EXB059.A2501","EXB015.A3301","EXB034.A2701","EXB059.A2201","EXB059.A2301","EXB059.A2401","LIB058.A0103","LIB058.A0106","LIB058.A0104")
poor_samples_mpa3 <- fread("./05-results.backup/cuperdec_mpa3_poor_samples.tsv") %>%
  pull(Sample)

outliersF <- str_c(outliers_mpa3, collapse = "|")

```

```{r load_metadata}

# load the metadata file
load("./05-results.backup/Metadata_tables.RData")

# read in the MALT mapped/unmapped gc and read length info from `MID_malt_map_unmap_rl_gc.Rmd`
malt_map_unmap_rl_gc <- fread("./05-results.backup/rl_gc_sub_data.tsv")
colnames(malt_map_unmap_rl_gc) <- gsub("_map","_malt_map", colnames(malt_map_unmap_rl_gc))
colnames(malt_map_unmap_rl_gc) <- gsub("_unmap","_malt_unmap", colnames(malt_map_unmap_rl_gc))

```

```{r strep_groups}
# load the MALT RefSeq taxonomy tables that have been decontaminated 
# and the column headers are cleaned up
# this is to get the Strep groups for coloring the PCA plot
load("./05-results.backup/Taxonomy_tables.RData")

# list poor samples from cuperdec
poor_samples_rs <- fread("./05-results.backup/cuperdec_poor_samples.tsv") %>%
  rename(Library_ID = Sample) %>%
  filter(str_detect(Library_ID, "MID")) %>%
  pull(Library_ID)

# we'll use the prevalence-filtered dataset
malt_rs <- all_species_decontam_prev %>%
  # select(matches("Species|MID|CMB")) %>%
  adorn_totals(where = "col")  %>%
  filter(Total >  0) %>%
  select(-Total) %>%
  select(-poor_samples_rs)

strep_groups <- fread("./00-documentation.backup/dRep_strep_groups.tsv") %>%
  # remove the extrac column with the old dRep
  select(-Clade_Consensus) %>%
  # make a factor for plotting
  mutate(dRep = fct_relevel(dRep, "Sanguinis","Mitis","Salivarius","Anginosus","Bovis","Pyogenic","Mutans","Other_oral","Other","Unknown"))

strep_rs <- malt_rs %>%
  filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., strep_groups) %>%
  select(Species, dRep, everything()) %>%
  # convert to long-format
  gather("Library_ID","Counts", 3:ncol(.)) %>%
  # mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs)) %>%
  dplyr::group_by(Library_ID, dRep) %>%
  summarize(Count_sum = sum(Counts)) %>%
  ungroup() %>%
  group_by(Library_ID) %>%
  mutate(Percent = Count_sum / sum(Count_sum)) %>%
  select(Library_ID, dRep, Percent) %>%
  pivot_wider(names_from = dRep, values_from = Percent)

```

```{r}
comb_metadata <- full_metadata %>%
  mutate(`DNA_molecules_per_library_x10^6_log` = log10(`DNA_molecules_per_library_x10^6`)) %>%
  full_join(., malt_map_unmap_rl_gc) %>%
  full_join(., strep_rs, by = "Library_ID")

```

## Middenbeemster
```{r pca_species_mid}
mpa3_species_decontam_mid <- mpa3_species_decontam %>%
  select(-one_of(outliers_mpa3)) %>%
  select(-one_of(poor_samples_mpa3)) %>%
  select(matches("Species|MID")) %>%
  gather("Library_ID","Counts",2:ncol(.)) %>% 
  mutate(Counts = Counts +1) %>%
  spread(Species,Counts) %>%
  column_to_rownames("Library_ID")

# prepare to run a PCA
# check the number of components to retain by tuning the PCA
mixOmics::tune.pca(mpa3_species_decontam_mid, logratio = 'CLR')

malt_otu.pca <- mixOmics::pca(mpa3_species_decontam_mid, ncomp = 2, logratio = 'CLR')

exp_var_mid <- paste0(round(malt_otu.pca$prop_expl_var$X * 100, 2), "%")

mid_pca_values <- malt_otu.pca$variates$X %>%
  as.data.frame() %>%
  rownames_to_column("Library_ID") %>%
  inner_join(., comb_metadata, by = "Library_ID") %>%
  drop_na(Site_code) %>%
  mutate(Sex_n = ifelse(Sex == "Female", 0,
                        ifelse(Sex == "Male", 1,2))) %>%
  mutate(Pipenotch_n = ifelse(Pipenotch == "Present",0,
                              ifelse(Pipenotch == "Absent",1,2))) %>%
  mutate(Age_n = ifelse(Age == "13-18",0,
                        ifelse(Age == "18-25",1,
                               ifelse(Age == "25-45",2,
                                      ifelse(Age == "45+",4,5)))))

ggplot(mid_pca_values, aes(PC1, PC2, color = Site_code, shape = Time_period)) +
  geom_point(size = 3) +
  theme_minimal() +
  scale_color_manual(values = Site_code_colors) +
  scale_shape_manual(values = Time_period_shapes) +
  xlab(paste("PC1 - ", exp_var_mid[1])) +
  ylab(paste("PC2 - ", exp_var_mid[2]))


fwrite(mid_pca_values, "./05-results.backup/mid_species_pca_values.tsv", sep = "\t", quote = F)

```

```{r mid_pc_correlations}
# Compute Canonical Correlation Analysis (CCA) 
# between all pairs of selected variables
# returns absolute correlation value

# rename vriables to look nice in figures
mid_pca_values_select <- mid_pca_values %>%
  select(Library_ID, PC1, PC2, seq_len_avg, gc_avg, No_reads_total, Sanguinis, Anginosus, Age_n, Sex_n, Pipenotch_n, `%AMTL`, `%teeth_with_caries`, calc_sup_SI_score, Peridontal_affect_score, `%_positions_with_Periodontal`, Max_Perio_Score, Calculus_extracted_mg, `extract_conc_ng/mg`, `extract_conc_ng/uL`, `extract_conc_after_storage_ng/uL`, `DNA_molecules_per_library_x10^6`,Calc_sub_SI_score, `%teeth_with_calc`, `%_positions_perioapical`) %>%
  rename(`Seq length` = seq_len_avg,
         GC = gc_avg,
         `Total reads` = No_reads_total,
         Age = Age_n,
         Sex = Sex_n,
         Pipenotch = Pipenotch_n,
         `% AMTL` = `%AMTL`,
         `% Caries` = `%teeth_with_caries`,
         `Supra calc score` = calc_sup_SI_score,
         `Perio score` = Peridontal_affect_score,
         `% Perio` = `%_positions_with_Periodontal`,
         `Max perio score` = Max_Perio_Score,
         `Extracted weight (mg)` = Calculus_extracted_mg,
         `Pre-storage [extract] (ng/mg)` = `extract_conc_ng/mg`,
         `Pre-storage [extract] (ng/uL)` = `extract_conc_ng/uL`,
         `Post-storage [extract] (ng/uL)` = `extract_conc_after_storage_ng/uL`,
         `[Library] (molecules)` = `DNA_molecules_per_library_x10^6`,
         `Sub calc score` = Calc_sub_SI_score,
         `% Calculus` = `%teeth_with_calc`,
         `% Perioapical` = `%_positions_perioapical`)

# select variables
form <- ~ PC1 + PC2 + `Seq length` + GC + `Total reads` + Sanguinis + Anginosus + Age + Sex + Pipenotch + `% AMTL` + `% Caries` + `Supra calc score` + `Perio score` + `% Perio` + `Max perio score` + `Extracted weight (mg)` + `Pre-storage [extract] (ng/mg)` + `Pre-storage [extract] (ng/uL)` + `Post-storage [extract] (ng/uL)` + `[Library] (molecules)` + `Sub calc score` + `% Calculus` + `% Perioapical`

# compute CCA
C_mid = canCorPairs( form, mid_pca_values_select)

# Plot correlation matrix
plotCorrMatrix(C_mid)


```

```{r pearson_corr_mid}
# test for significant differences in diversity between the metadata categories

pearson_mid <- mid_pca_values %>%
rstatix::cor_test(., PC1, PC2, seq_len_avg, gc_avg, No_reads_total, Sanguinis, Anginosus, Age_n, Sex_n, Pipenotch_n, `%AMTL`, `%teeth_with_caries`, calc_sup_SI_score, Peridontal_affect_score, `%_positions_with_Periodontal`, Max_Perio_Score, Calculus_extracted_mg, `extract_conc_ng/mg`, `extract_conc_ng/uL`, `extract_conc_after_storage_ng/uL`, `DNA_molecules_per_library_x10^6`,Calc_sub_SI_score, `%teeth_with_calc`, `%_positions_perioapical`, method="pearson")

pearson_mid

pearson_mid %>%
  mutate(same = var1 == var2) %>%
  filter(same == FALSE) %>%
  select(-same) %>%
  filter(p <= 0.001) %>%
  filter(cor > 0.40 | cor < -0.40) %>%
  distinct(statistic, .keep_all = TRUE)
  
```

```{r}

C_mid %>%
  as_data_frame(.) %>%
  mutate(names = rownames(C_mid)) %>%
  select(names, everything()) %>%
  pivot_longer(!names, names_to = "Corrs", values_to = "values") %>%
  filter(values != 1) %>%
  filter(values >= 0.4) %>%
  distinct(values, .keep_all = TRUE)

```

```{r mid_corrs, eval = F}

C_mid %>%
  as_tibble(.) %>% 
  mutate(names = rownames(C_mid)) %>% 
  select(names, everything()) %>%
  filter(!str_detect(names, "PC")) %>%
  select(matches("name|PC1|PC2")) %>%
  arrange(PC1) %>%
  mutate(names = fct_relevel(names, names)) %>%
  pivot_longer(!names, names_to = "Component", values_to = "Correlation") %>%
  ggplot(., aes(Component, names, fill = Correlation)) +
    geom_tile() +
    scale_fill_gradient(low = "white", high = "#311068") +
    theme_minimal(base_size = 9) +
    theme(axis.text.x = element_text(angle = 90, hjust = 0.95), # , color = vector_color
          plot.margin = margin(0, 0, 0, 0, "pt"),
          axis.title.y = element_blank(),
          legend.position = "left")


newcolors <- scale_fill_gradient(low = "white", high = "#311068")

```

```{r}
# colorset <- rev(colorspace::sequential_hcl(10, palette = "BuPu"))

colorset <- c("#ffffff","#e8e2ee","#d1c6dc","#baaacb","#a48fba","#8d74aa","#775b99","#604289","#492978","#311068")

pvals_mid <- mid_pca_values_select %>%
  column_to_rownames("Library_ID") %>%
  as.matrix(.) %>%
  corrplot::cor.mtest(., method="pearson")

mid_corr_plot <- C_mid %>%
  corrplot::corrplot(., p.mat = pvals_mid$p, order = "hclust", type = "upper", col = colorset, is.corr = FALSE, cl.cex = 0.95, diag = FALSE, #tl.srt = 45,
                     tl.col = 'black', sig.level = c(0.001), pch.cex = 1.2, insig = 'label_sig', pch.col = 'grey20')
mid_corr_plot

```


```{r, eval = F}
svg(file = "./06-publication/supplemental_figures/SXX9/mid_corr_plot.svg") 

C_mid %>%
  corrplot::corrplot(., p.mat = pvals_mid$p, order = "hclust", type = "upper", col = colorset, is.corr = FALSE, cl.cex = 0.95, diag = FALSE, #tl.srt = 45,
                     tl.col = 'black', sig.level = c(0.001), pch.cex = 1.2, insig = 'label_sig', pch.col = 'grey20')


dev.off()

```


## All Sites

```{r pca_species_all}
mpa3_species_decontam_unfilt <- mpa3_species_decontam %>%
  select(-one_of(outliers_mpa3)) %>%
  select(-one_of(poor_samples_mpa3)) %>%
  select(-matches("EXB|LIB|CSN|CSD|ARS|CSS|CSL")) %>%
  gather("Library_ID","Counts",2:ncol(.)) %>%
  mutate(Counts = Counts +1) %>%
  spread(Species,Counts) %>%
  column_to_rownames("Library_ID")

# prepare to run a PCA
# check the number of components to retain by tuning the PCA
tune.pca(mpa3_species_decontam_unfilt, logratio = 'CLR')

pca.list <- mixOmics::pca(mpa3_species_decontam_unfilt, ncomp = 5, logratio = 'CLR')

exp_var_all <- paste0(round(pca.list$prop_expl_var$X * 100, 2), "%")
all_pca_values <- pca.list$variates$X %>%
          as.data.frame() %>%
          rownames_to_column("Library_ID") %>%
          inner_join(comb_metadata, by = "Library_ID") %>%
          inner_join(., strep_rs) %>%
  drop_na(Site_code) %>%
  mutate(Time_period_n = ifelse(Time_period == "Medieval",0,
                                ifelse(Time_period == "Industrial",1,2))) %>%
  mutate(Site_code_n = ifelse(Site_code == "MID",0,
                              ifelse(Site_code == "CMB",1,
                                     ifelse(Site_code == "RAD",2,
                                            ifelse(Site_code == "KIL",3,
                                                   ifelse(Site_code == "ELR",4,
                                                          ifelse(Site_code == "IVE",5,
                                                                 ifelse(Site_code == "JAE",6,7))))))))

ggplot(all_pca_values, aes(PC1, PC2, color = Site_code, shape = Time_period)) +
  geom_point(size = 3) +
  theme_minimal() +
  scale_color_manual(values = Site_code_colors) +
  scale_shape_manual(values = Time_period_shapes) +
  xlab(paste("PC1 - ", exp_var_all[1])) +
  ylab(paste("PC2 - ", exp_var_all[2]))

```

```{r all_corrs}
# rename variables to look nice in figures
all_pca_values_select <- all_pca_values %>%
  select(Library_ID,PC1, PC2, seq_len_avg, gc_avg, No_reads_total, Sanguinis, Anginosus, Time_period_n, Site_code_n) %>%
  rename(`Seq length` = seq_len_avg,
         GC = gc_avg,
         `Total reads` = No_reads_total,
         `Time period` = Time_period_n,
         Site = Site_code_n)

form <- ~ PC1 + PC2 + `Seq length` + GC + `Total reads` + Sanguinis + Anginosus + `Time period` + Site
C_all = canCorPairs(form, all_pca_values_select)
plotCorrMatrix( C_all )


```


```{r pearson_corr_mid}
# test for significant differences in diversity between the metadata categories

pearson_all <- all_pca_values %>%
rstatix::cor_test(., PC1, PC2, PC3, seq_len_avg, gc_avg, No_reads_total, Sanguinis, Anginosus, Time_period_n, Site_code_n, method="pearson")

pearson_all

pearson_all %>%
  mutate(same = var1 == var2) %>%
  filter(same == FALSE) %>%
  select(-same) %>%
  filter(p <= 0.001) %>%
  filter(cor > 0.40 | cor < -0.40) %>%
  distinct(statistic, .keep_all = TRUE)
  
```

```{r}

C_all %>%
  as_data_frame(.) %>%
  mutate(names = rownames(C_all)) %>%
  select(names, everything()) %>%
  pivot_longer(!names, names_to = "Corrs", values_to = "values") %>%
  filter(values != 1) %>%
  filter(values >= 0.4) %>%
  distinct(values, .keep_all = TRUE)


C_all %>%
  as_data_frame(.) %>%
  mutate(names = rownames(C_all)) %>%
  select(names, everything()) %>%
  pivot_longer(!names, names_to = "Corrs", values_to = "values") %>%
  filter(names == "PC1") %>%
  arrange(desc(values))

```


```{r}
# colorset <- rev(colorspace::sequential_hcl(10, palette = "BuPu"))

colorset <- c("#ffffff","#e8e2ee","#d1c6dc","#baaacb","#a48fba","#8d74aa","#775b99","#604289","#492978","#311068")

 pvals_all <- all_pca_values_select %>%
  column_to_rownames("Library_ID") %>%
  as.matrix(.) %>%
  corrplot::cor.mtest(., method="pearson")

C_all %>%
  corrplot::corrplot(., p.mat = pvals_all$p, order = "hclust", type = "upper", col = colorset, is.corr = FALSE, cl.cex = 1.0, diag = FALSE, #tl.srt = 45,
                     tl.col = 'black', sig.level = c(0.001), pch.cex = 2.0, insig = 'label_sig', pch.col = 'grey20')

```

```{r, eval = F}
svg(file = "./06-publication/main_figures/Figure_XX5/all_corr_plot.svg") 

C_all %>%
  corrplot::corrplot(., p.mat = pvals_all$p, order = "hclust", type = "upper", col = colorset, is.corr = FALSE, cl.cex = 1.0, diag = FALSE, #tl.srt = 45,
                     tl.col = 'black', sig.level = c(0.001), pch.cex = 2.0, insig = 'label_sig', pch.col = 'grey20')

dev.off()

```











