---
title: "MID/CMB, Radcliffe, Kilteasheen, Iberian medieval calculus metadata and colors"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---

```{r load_libraries, echo = F, message = F}
library(knitr)
library(data.table)
library(microshades)
library(tidyverse)

```

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

```{r}
load("./05-results.backup/Metadata_tables.RData")
```

```{r}

full_metadata %>%
  select(matches("Library_ID|Pipe|Perio")) %>%
  filter(str_detect(Library_ID, "MID"))

```


```{r}

plot1 <- full_metadata %>%
  select(matches("Library_ID|Pipe|Perio|calc")) %>%
  filter(str_detect(Library_ID, "MID")) %>%
  drop_na(Min_no_Pipe_notches) %>%
  ggplot(., aes(x = Min_no_Pipe_notches, y = `%_positions_with_Periodontal`, color = Calc_sub_SI_score)) +
    geom_smooth(method = "lm", color = "black", fill = "grey80", size = 0.75) +
    geom_point(size = 2) +
    theme_minimal() +
    # scale_colour_gradient(low = "blue", high = "red", na.value = NA) +
    theme(axis.text.x = element_text(angle = 0, hjust = 1, vjust = 0.5),
          text = element_text(size=12)) +
    ylab("% positions with periodontal disease") +
    ggtitle("")

plot1

```

Modified from `https://stackoverflow.com/questions/7549694/add-regression-line-equation-and-r2-on-graph`
```{r}
# GET EQUATION AND R-SQUARED AS STRING
# SOURCE: https://groups.google.com/forum/#!topic/ggplot2/1TgH-kG5XMA

df <- full_metadata %>%
  select(matches("Library_ID|Pipe|Perio")) %>%
  filter(str_detect(Library_ID, "MID")) %>%
  drop_na(Min_no_Pipe_notches)

lm_eqn <- function(df){
    m <- lm(`%_positions_with_Periodontal` ~ Min_no_Pipe_notches, df);
    eq <- substitute(italic(y) == a + b %.% italic(x)*","~~italic(r)^2~"="~r2, 
         list(a = format(unname(coef(m)[1]), digits = 2),
              b = format(unname(coef(m)[2]), digits = 2),
             r2 = format(summary(m)$r.squared, digits = 3)))
    as.character(as.expression(eq));
}

p1 <- plot1 + geom_text(x = 2.5, y = 12.5, label = lm_eqn(df), parse = TRUE, size = 3)
p1

```


```{r}

plot2 <- full_metadata %>%
  select(matches("Library_ID|Pipe|Perio|AMTL")) %>%
  filter(str_detect(Library_ID, "MID")) %>%
  drop_na(Pipenotch) %>%
  ggplot(., aes(x = Min_no_Pipe_notches, y = Max_Perio_Score, color = `%AMTL`)) +
    geom_smooth(method = "lm", color = "black", fill = "grey80", size = 0.75) +
    ggpointgrid::geom_pointrect(scale_x = 0.08, scale_y = 0.08) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 0, hjust = 1, vjust = 0.5),
          text = element_text(size=12)) +
    scale_colour_gradient(low = "blue", high = "red", na.value = NA) +
    ylab("Max perio score") +
    ggtitle("")


lm_eqn <- function(df){
    m <- lm(Max_Perio_Score ~ Min_no_Pipe_notches, df);
    eq <- substitute(italic(y) == a + b %.% italic(x)*","~~italic(r)^2~"="~r2, 
         list(a = format(unname(coef(m)[1]), digits = 2),
              b = format(unname(coef(m)[2]), digits = 2),
             r2 = format(summary(m)$r.squared, digits = 3)))
    as.character(as.expression(eq));
}

p2 <- plot2 + geom_text(x = 2.5, y = 2.5, label = lm_eqn(df), parse = TRUE, size = 3)
p2

```



```{r}

full_metadata %>%
  select(matches("Library_ID|Pipe|AMTL")) %>%
  filter(str_detect(Library_ID, "MID")) %>%
  drop_na(Min_no_Pipe_notches) %>%
  ggplot(., aes(x = Min_no_Pipe_notches, y = `%AMTL`)) +
    geom_point(size = 2, color = "grey50") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 0, hjust = 1, vjust = 0.5),
          text = element_text(size=12)) +
    geom_smooth(method = "lm", color = "black", fill = "grey80", size = 0.75) +
    ylab("% AMTL") +
    ggtitle("")

```

```{r plot_test}
full_metadata %>%
  filter(str_detect(Library_ID, "MID")) %>%
  drop_na(Pipenotch) %>%
  ggplot(., aes(x = factor(Max_Perio_Score), y = Age, color = Sex, shape = Pipenotch, size = `%AMTL`)) +
    ggpointgrid::geom_pointrect(scale_x = 0.16, scale_y = 0.18) +
    theme_minimal() +
    scale_shape_manual(values = c(15, 7)) +
    scale_color_manual(values = c("green","yellow","gray")) +
    theme(axis.text = element_text(size = 10)) +
    xlab("Max. periodontitis score") +
    ylab("Age group")

```

```{r smoking_pd}
hex_df <- default_hex(6, TRUE)

full_metadata %>%
  filter(str_detect(Library_ID, "MID")) %>%
  drop_na(Pipenotch) %>%
  ggplot(., aes(x = Pipenotch, y = Age, color = Peridontal_affect_score, shape = Sex, size = `%AMTL`)) +
    ggpointgrid::geom_pointrect(scale_x = 0.14, scale_y = 0.22) +
    theme_minimal() +
    # scale_shape_manual(values = c(15, 7)) +
    scale_colour_gradient(low = "blue", high = "red") +
    # scale_color_manual(values = microshades_palette("micro_green")) +
    theme(axis.text = element_text(size = 10)) +
    xlab("Pipe notch(es)") +
    ylab("Age group")

```

```{r smoking_caries}
full_metadata %>%
  filter(str_detect(Library_ID, "MID")) %>%
  drop_na(Pipenotch) %>%
  ggplot(., aes(x = Pipenotch, y = Age, color = `%teeth_with_caries`, shape = Sex, size = `%AMTL`)) +
    ggpointgrid::geom_pointrect(scale_x = 0.14, scale_y = 0.22) +
    theme_minimal() +
    # scale_shape_manual(values = c(15, 7)) +
    scale_colour_gradient(low = "blue", high = "red") +
    theme(axis.text = element_text(size = 10)) +
    xlab("Pipe notch(es)") +
    ylab("Age group")

```

```{r}

full_metadata %>%
  filter(str_detect(Library_ID, "MID")) %>%
  drop_na(Pipenotch) %>%
  ggplot(., aes(x = Calculus_extracted_mg, y = `extract_conc_ng/mg`, color = calc_sup_SI_score, shape = Pipenotch)) +
    geom_point(size = 2.5) +
    theme_minimal() +
    scale_shape_manual(values = c(12, 13)) +
    # scale_color_manual(values = c("green","yellow","gray")) +
    theme(axis.text = element_text(size = 10)) +
    xlab("weight extracted calculus (mg)") +
    ylab("extract concentration (ng/mg")




```















