---
title: "MID/CMB Strep group distributions"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---

```{r load_libraries, echo = F, message = F}
library(knitr)
library(data.table)
library(janitor)
library(tidyverse)
library(cowplot)
opts_chunk$set(echo=F, warning=F, message=F, dpi=150)
```

Set the working directory of the notebook to the parent directory of the 
notebook itself.  

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

```{r}
# read in the Strep group table James made for the Deep Evo project

strep_groups <- fread("./00-documentation.backup/25-streptococcus_cladegroup_amylasegroup_database.tsv") %>%
  select(Taxon, Clade_Consensus) %>%
  rename(Species = Taxon) %>%
  mutate(Species = str_replace_all(Species, "_", " ")) %>%
  mutate(Clade_Consensus = fct_relevel(Clade_Consensus, "sanguinis","mitis","salivarius","anginosus","bovis","pyogenic","mutans","unknown","NA"))

```

```{r}
# set colors to resemble James' figure

clade_colors <- c("sanguinis" = "#a50026",
                  "mitis" = "#d73027",
                  "salivarius" = "#f46d43",
                  "anginosus" = "#fee090",
                  "pyogenic" = "#74add1",
                  "mutans" = "#4575b4",
                  "bovis" = "#abd9e9",
                  "unknown" = "#313695",
                  "NA" = "grey50")

genus_colors <- c("Streptococcus" = "#a50026", "Other" = "#313695")

```


## MALT RefSeq
```{r load_MALT_RefSeq_data}

# load the MALT RefSeq taxonomy tables that have been decontaminated and the column headers are cleaned up
load("./05-results.backup/Taxonomy_tables.RData")

# list poor samples from cuperdec
poor_samples_rs <- fread("./05-results.backup/cuperdec_poor_samples.tsv") %>%
  rename(Library_ID = Sample) %>%
  filter(str_detect(Library_ID, "MID")) %>%
  pull(Library_ID)

# we'll use the prevalence-filtered dataset
malt_rs <- all_species_decontam_prev %>%
  select(matches("Species|MID|CMB")) %>%
  adorn_totals(where = "col")  %>%
  filter(Total >  0) %>%
  select(-Total) %>%
  select(-poor_samples_rs)


```

```{r malt_rs_graphs}

# set the order of samples based on proportion of sanguinis and agninosis
# need to get the proportion of each for this
# then arrange by proportion

sample_order_rs <- malt_rs  %>%
  filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., strep_groups) %>%
  select(-Species) %>%
  select(Clade_Consensus, everything()) %>%
  # long-format
  gather("Library_ID","Counts", 2:ncol(.)) %>%
  # sum together all species per group
  group_by(Library_ID, Clade_Consensus) %>%
  summarize(Reads = sum(Counts)) %>%
  # transpose
  spread(Clade_Consensus, Reads) %>%
  # convert table to proportions
  adorn_percentages(denominator = "row") %>%
  # arrange by sanguinis and for the ones w/o sanguinis, by anginosis
  arrange(desc(sanguinis), anginosus)%>%
  pull(Library_ID)


malt_rs %>%
  filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., strep_groups) %>%
  select(Species, Clade_Consensus, everything()) %>%
  # convert to long-format
  gather("Library_ID","Counts", 3:ncol(.)) %>%
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs)) %>%
  dplyr::group_by(Library_ID, Clade_Consensus) %>%
  summarize(Count_sum = sum(Counts)) %>%
  ggplot(., aes(x = Library_ID, y = Count_sum, fill = Clade_Consensus)) +
         geom_bar(position = "fill", stat = "identity") + # , color = "black"
         theme_minimal(base_size = 14) +
         scale_fill_manual(values = clade_colors) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1),
               axis.text = element_text(size = 8)) +
         # scale_y_continuous(breaks=scales::pretty_breaks(n=6)) +
         ylab("Proportion Strep group") +
         ggtitle("")

```

```{r save_rs_order, eval = F}

sample_order_rs %>%
  as.data.frame(.) %>%
 rename(Library_ID = ".") %>%
fwrite(., "./05-results.backup/malt_rs_Strep_group_order.tsv", sep = "\t", quote = F)

```

```{r rs_strep_proportion}

strep_prop <- malt_rs %>%
  # make a column with Strep or other
  mutate(Genus = ifelse(str_detect(Species,"Strep"),"Streptococcus","Other")) %>%
  # remove Species column leaving Genus column
  select(Genus, everything()) %>%
  select(-Species) %>%
  # convert to long format
  gather("Library_ID","Counts", 2:ncol(.)) %>%
  group_by(Library_ID, Genus) %>%
  # sum all Strep read counts and all Other read counts
  summarize(Reads = sum(Counts)) %>%
  spread(Genus, Reads) %>%
  # convert to proportions
  adorn_percentages() %>%
  ungroup()

strep_prop %>%
  gather("Genus","Counts", 2:ncol(.)) %>%
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs)) %>%
  arrange(Library_ID) %>%
  ggplot(., aes(x = Library_ID, y = Counts, fill = Genus)) +
         geom_bar(stat = "identity") + # , color = "black"
         theme_minimal(base_size = 14) +
         scale_fill_manual(values = genus_colors) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1),
               axis.text = element_text(size = 8)) +
         # scale_y_continuous(breaks=scales::pretty_breaks(n=6)) +
         ylab("Proportion Strep group") +
         ggtitle("")

```


## MALT nt
```{r load_MALT_nt_data}
# read in the species table
nt_raw <- fread("./05-results.backup/MID_CMB_malt_nt-comparison-species.txt")

# clean the file names
nt_raw <- rename(nt_raw, Species = `#Datasets`)
colnames(nt_raw) <- gsub(".unmapped","", colnames(nt_raw))
colnames(nt_raw) <- gsub(".10M","", colnames(nt_raw))

# remove human and unassigned reads, convert NA to 0, and remove the 8 MID samples with no metadata
nt_raw <- nt_raw %>% 
  filter(!str_detect(Species, "Homo sapiens|Not assigned")) %>%
  replace(is.na(.), 0) %>%
  # these samples have no metadata
  select(-c("MID025.A0101","MID033.A0101","MID052.A0101","MID056.A0101","MID065.A0101","MID068.A0101","MID076.A0101","MID078.A0101")) %>%
  arrange(Species)

```

Now decontam the tables
```{r nt_decontam}
nt_contaminants <- fread("./05-results.backup/contaminant_species_nt.tsv", sep = "\t")
poor_samples_nt <- fread("./05-results.backup/cuperdec_nt_poor_samples.tsv") %>%
  pull(Sample)

# remove contaminant species from nt table
nt_species_decontam <- nt_raw %>%
  anti_join(., nt_contaminants) %>%
  select(-poor_samples_nt)

# and remove poorly preserved samples
malt_nt <- nt_species_decontam %>%
  select(matches("Species|MID|CMB")) %>%
  adorn_totals(where = "col")  %>%
  filter(Total >  0) %>%
  select(-Total)

```

```{r}

sample_order_nt <- malt_nt %>%
  filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., strep_groups) %>%
  select(-Species) %>%
  select(Clade_Consensus, everything()) %>%
  # transpose
  gather("Library_ID","Counts", 2:ncol(.)) %>%
  group_by(Library_ID, Clade_Consensus) %>%
  summarize(Reads = sum(Counts)) %>%
  spread(Clade_Consensus, Reads) %>%
  # convert table to proportions
  adorn_percentages(denominator = "row") %>%
  # arrange by sanguinis and for the ones w/o sanguinis, by anginosis
  arrange(desc(sanguinis), anginosus) %>%
  pull(Library_ID)


plot_nt <- malt_nt %>%
  filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., strep_groups) %>%
  select(Species, Clade_Consensus, everything()) %>%
  # convert to long-format
  gather("Library_ID","Counts", 3:ncol(.)) %>%
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_nt)) %>%
  dplyr::group_by(Library_ID, Clade_Consensus) %>%
  summarize(Count_sum = sum(Counts)) %>%
  ggplot(., aes(x = Library_ID, y = Count_sum, fill = Clade_Consensus)) +
         geom_bar(position = "fill", stat = "identity") + # , color = "black"
         theme_minimal(base_size = 14) +
         scale_fill_manual(values = clade_colors) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1),
               axis.text = element_text(size = 8)) +
         # scale_y_continuous(breaks=scales::pretty_breaks(n=6)) +
         ylab("Proportion Strep group") +
         ggtitle("")

plot_nt

# ggsave("~/Desktop/MID_strep_groups_MALT_nt.pdf", plot = plot_nt, device = "pdf",
#        scale = 1, width = 9, height = 5, units = c("in"), dpi = 300)

```

```{r save_nt_order}

sample_order_nt %>%
  as.data.frame(.) %>%
 rename(Library_ID = ".") %>%
fwrite(., "./05-results.backup/malt_nt_Strep_group_order.tsv", sep = "\t", quote = F)

```

```{r nt_strep_proportion}

strep_prop_nt <- malt_nt %>%
  # make a column with Strep or other
  mutate(Genus = ifelse(str_detect(Species,"Strep"),"Streptococcus","Other")) %>%
  # remove Species column leaving Genus column
  select(Genus, everything()) %>%
  select(-Species) %>%
  # convert to long format
  gather("Library_ID","Counts", 2:ncol(.)) %>%
  group_by(Library_ID, Genus) %>%
  # sum all Strep read counts and all Other read counts
  summarize(Reads = sum(Counts)) %>%
  spread(Genus, Reads) %>%
  # convert to proportions
  adorn_percentages() %>%
  ungroup()

strep_prop_nt %>%
  gather("Genus","Counts", 2:ncol(.)) %>%
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_nt)) %>%
  arrange(Library_ID) %>%
  ggplot(., aes(x = Library_ID, y = Counts, fill = Genus)) +
         geom_bar(stat = "identity") + # , color = "black"
         theme_minimal(base_size = 14) +
         scale_fill_manual(values = genus_colors) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1),
               axis.text = element_text(size = 8)) +
         # scale_y_continuous(breaks=scales::pretty_breaks(n=6)) +
         ylab("Proportion Strep group") +
         ggtitle("")

```

## MetaPhlAn3
Note that MetaPhlAn3 didn't pick up any strep outside of sanguinis and mitis
groups. This means that for several samples, no Strep were detected.
```{r load_mpa3_data}
# read in the species table
mpa3_raw <- fread("./05-results.backup/abundance_table_mpa3.tsv") %>%
  select(-NCBI_tax_id)

# clean the file names
colnames(mpa3_raw) <- gsub(".metaphlan3","", colnames(mpa3_raw))

# filter to have only species
mpa3_sp <- mpa3_raw %>% 
  filter(str_detect(clade_name, "s__")) %>%
  separate(clade_name, into = c("K","P","C","O","F","G","Species"), sep = "\\|") %>%
  select(-c("K","P","C","O","F","G")) %>%
  mutate(Species = str_replace_all(Species, "s__",""),
         Species = str_replace_all(Species, "_"," ")) %>%
  # these samples have no metadata
  select(-c("MID025.A0101","MID033.A0101","MID052.A0101","MID056.A0101","MID065.A0101","MID068.A0101","MID076.A0101","MID078.A0101")) %>%
  arrange(Species)

```


Now decontam the tables
```{r mpa3_decontam}
mpa3_contaminants <- fread("./05-results.backup/contaminant_species_mid_mpa3.tsv", sep = "\t") %>%
  bind_rows(., fread("./05-results.backup/contaminant_species_kilteasheen_mpa3.tsv", sep = "\t")) %>%
  bind_rows(., fread("./05-results.backup/contaminant_species_iberia_mpa3.tsv", sep = "\t")) %>%
  unique()

# remove contaminant species from nt table
mpa3_species_decontam <- mpa3_sp %>%
  anti_join(., mpa3_contaminants)

mpa3 <- mpa3_species_decontam %>%
  select(matches("Species|MID|CMB")) %>%
  adorn_totals(where = "col")  %>%
  filter(Total >  0) %>%
  select(-Total)


```

```{r mpa3_graphs}
sample_order_mpa3 <- mpa3 %>%
  filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., strep_groups) %>%
  select(-Species) %>%
  select(Clade_Consensus, everything()) %>%
  # transpose
  gather("Library_ID","Counts", 2:ncol(.)) %>%
  group_by(Library_ID, Clade_Consensus) %>%
  summarize(Reads = sum(Counts)) %>%
  spread(Clade_Consensus, Reads) %>%
  # convert table to proportions
  adorn_percentages(denominator = "row") %>%
  # arrange by sanguinis and for the ones w/o sanguinis, by anginosis
  arrange(desc(sanguinis)) %>%
  pull(Library_ID)


mpa3 %>%
  filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., strep_groups) %>%
  select(Species, Clade_Consensus, everything()) %>%
  # convert to long-format
  gather("Library_ID","Counts", 3:ncol(.)) %>%
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_mpa3))%>%
  dplyr::group_by(Library_ID, Clade_Consensus) %>%
  summarize(Count_sum = sum(Counts)) %>%
  ggplot(., aes(x = Library_ID, y = Count_sum, fill = Clade_Consensus)) +
         geom_bar(position = "fill", stat = "identity") + # , color = "black"
         theme_minimal(base_size = 14) +
         scale_fill_manual(values = clade_colors) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1),
               axis.text = element_text(size = 8)) +
         # scale_y_continuous(breaks=scales::pretty_breaks(n=6)) +
         ylab("Proportion Strep group") +
         ggtitle("")

```

```{r save_mpa3_order}

sample_order_mpa3 %>%
  as.data.frame(.) %>%
 rename(Library_ID = ".") %>%
fwrite(., "./05-results.backup/mpa_Strep_group_order.tsv", sep = "\t", quote = F)

```


