---
title: "Smoking calcululs Figure XX1"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---


```{r load_libraries, echo = F, message = F}
library(knitr)
library(data.table)
library(janitor)
library(cuperdec)
library(tidyverse)
library(cowplot)
opts_chunk$set(echo=F, warning=F, message=F, dpi=150)
```

Set the working directory of the notebook to the parent directory of the 
notebook itself.  

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```


##Cumulative Percent Decay Curves
```{r load_data}
# read in the species table
mid_raw <- fread("./05-results.backup/MID_malt_bactarchhomo2018_comparison-species.txt")
radcliffe_raw <- fread("./05-results.backup/Radcliffe_pfuT_comparison-species.txt")
kilteasheen_raw <- fread("./05-results.backup/Kilteasheen_comparison-species.txt")
iberian_raw <- fread("./05-results.backup/iberian_medieval_malt_species_raw.tsv")


all_raw <- mid_raw %>%
  full_join(., radcliffe_raw) %>%
  full_join(., kilteasheen_raw) %>%
  full_join(., iberian_raw)


# clean the file names
all_raw <- rename(all_raw, Species = `#Datasets`)
colnames(all_raw) <- gsub(".unmapped","", colnames(all_raw))
colnames(all_raw) <- gsub("MeganServer::","", colnames(all_raw))

# remove human and unassigned reads, convert NA to 0, and remove the 8 MID samples with no metadata
all_raw <- all_raw %>% 
  filter(!str_detect(Species, "Homo sapiens|Not assigned")) %>%
  replace(is.na(.), 0) %>%
  # these samples have no metadata
  select(-c("MID025.A0101","MID033.A0101","MID052.A0101","MID056.A0101","MID065.A0101","MID068.A0101","MID076.A0101","MID078.A0101")) %>%
  arrange(Species)


```

Load metadata
```{r load_metadata}

metadata <- fread("00-documentation.backup/MID_analysis_metadata.tsv") %>%
  select(Site_code, Library_ID) %>%
  full_join(., fread("./00-documentation.backup/radcliffe_pfuT_metadata.tsv") %>%
            select(Site_code, Library_ID)) %>%
  full_join(., fread("./00-documentation.backup/kilteasheen_metadata.tsv") %>%
            select(Site_code, Library_ID)) %>%
  full_join(., fread("./00-documentation.backup/iberian_medieval_metadata.tsv") %>%
            select(Site_code, Library_ID))

#set the columns of interest to factors
metadata <- metadata %>%
  as_tibble() %>%
  mutate(Site_code = fct_relevel(Site_code, "MID","CMB","RAD","KIL","ELR",
                                "IVE","JAE","VLC","EXB","LIB"))

```

Use the example database
```{r set_database}
# load the example database
example_database <- system.file("extdata",
                                "example_database.tsv",
                                package = "cuperdec")

# convert the example database to a tibble
database <- load_database(example_database, target = "oral") # %>% print()

```

```{r taxatable}

taxatable <- load_taxa_table(all_raw) # %>% print()

```

```{r metamap}
metadata_map <- load_map(metadata,
                     sample_col = "Library_ID",
                     source_col = "Site_code") # %>% print()

```

```{r simple_curve}
curves <- calculate_curve(taxatable, database = database) %>%
  print()

plot_cuperdec(curves)

```

```{r hard_rank_burnin}

rank_burnin_result <- hard_burnin_filter(curves, percent_threshold = 50, rank_burnin = 0.7) # percent_threshold = 50, rank_burnin = 0.7 allows only the highest ExtractionBlank line to turn turquoise, and the 2 library samples that really look like samples stay turquoise
# plot_cuperdec(curves, metadata_map, rank_burnin_result)

# restrict the plot to only the 1st 250 taxa
cd_curve_plot <- plot_cuperdec(curves, metadata_map, rank_burnin_result, restrict_x = 75)
cd_curve_plot

# ggsave("~/Desktop/MID_cuperdec_rank7_pct50.pdf", plot = cd_curve_plot, device = "pdf",
#        scale = 1, width = 7, height = 5, units = c("in"), dpi = 300)

```

##SourceTracker

```{r load_data}

# load the taxonomy tables that have been decontaminated and the column headers are cleaned up
load("./05-results.backup/Taxonomy_tables.RData")


# load the metadata file
load("./05-results.backup/Metadata_tables.RData")

# full_metadata <- full_metadata %>%
#   mutate(`DNA_molecules_per_library_x10^6_log` = log10(`DNA_molecules_per_library_x10^6`))

outliers <- c("EXB059.A2501","LIB058.A0103","LIB058.A0106","CSS","CSD")
poor_samples <- fread("./05-results.backup/cuperdec_poor_samples.tsv") %>%
  pull(Sample)

```

```{r load_sourcetracker_out}
full_source_results <- fread("./05-results.backup/sink_predictions_full_sources_rarefied_51500.tsv")

reduced_source_results <- fread("./05-results.backup/sink_predictions_reduced_sources_rarefied_51500.tsv")

```

```{r set_colors}
full_colors <- c(modernCalculus = "#80b1d3", subPlaque = "#8dd3c7", supPlaque = "#b3de69", urbanGut = "#fccde5",  ruralGut = "#fb8072", skin = "#ffffb3", sediment = "#bebada", boneARS = "#fdb462", Unknown = "#d9d9d9")
```


Get the samples ordered by decreasing amount of modern calculus
```{r}
samples_order_full <- full_source_results %>%
  rename(Library_ID = SampleID) %>%
  full_join(., full_metadata %>%
              select(Library_ID, Site), by = "Library_ID") %>%
  mutate(Oral = modernCalculus + subPlaque + supPlaque) %>%
  arrange(Site, desc(Oral)) %>%
  pull(Library_ID)

samples_order_reduced <- reduced_source_results %>%
  rename(Library_ID = SampleID) %>%
  full_join(., full_metadata %>%
              select(Library_ID, Site), by = "Library_ID") %>%
  mutate(Oral = modernCalculus + plaque) %>%
  arrange(Site, desc(Oral)) %>%
  pull(Library_ID)

```


Plot bar charts
```{r}

st_full_plot_all <- full_source_results %>%
  filter(!str_detect(SampleID, outliers %>% str_c(collapse = "|"))) %>%
  filter(!str_detect(SampleID, poor_samples %>% str_c(collapse = "|"))) %>%
  gather("Sources", "Percent",2:ncol(.)) %>%
  mutate(Percent = Percent * 100) %>%
  mutate(Sources = fct_relevel(Sources, "Unknown","boneARS","sediment","skin","urbanGut","ruralGut","subPlaque","supPlaque","modernCalculus"),
         SampleID = fct_relevel(SampleID, samples_order_full)) %>%
  
  filter(!str_detect(SampleID, "CMB")) %>%
  ggplot(., aes(x = SampleID, y = Percent, fill = Sources)) +
         geom_bar(stat = "identity") + # , color = "black"
         theme_minimal(base_size = 14) +
         scale_fill_manual(values = full_colors) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1),
               axis.text = element_text(size = 8)) +
         geom_hline(yintercept=75, linetype="dotted") +
         geom_hline(yintercept=90, linetype="dotted", color = "gray50") +
         # scale_y_continuous(breaks=scales::pretty_breaks(n=6)) +
         ylab("% attributed to source") +
         ggtitle("Full sources")
st_full_plot_all

# ggsave("~/Desktop/MID_st_full_plot_all.pdf", plot = st_full_plot_all, device = "pdf",
#        scale = 1, width = 16, height = 5, units = c("in"), dpi = 300)

```


What if we look at only the MID and CMB samples, and we order them by the PCA
PC1 order?
```{r}
# prep the table

outliers <- c("EXB059.A2501","LIB058.A0103","LIB058.A0106","CSS","CSD")
poor_samples <- fread("./05-results.backup/cuperdec_poor_samples.tsv") %>%
  pull(Sample)

malt_otu_pca_table <- all_species_decontam_prev %>%
  select(matches("Species|MID|CMB")) %>%
  select(-one_of(outliers)) %>%
  select(-one_of(poor_samples)) %>%
  gather("Library_ID","Counts",2:ncol(.)) %>%
  mutate(Counts = Counts + 1) %>%
  spread(Species, Counts) %>%
  column_to_rownames("Library_ID")

# perform a PCA to see how the data cluster
malt_otu.pca <- mixOmics::pca(malt_otu_pca_table, ncomp = 2, logratio = 'CLR')
malt_pca_values <- malt_otu.pca$variates$X %>%
  as.data.frame() %>%
  rownames_to_column("Library_ID") %>%
  inner_join(., full_metadata, by = "Library_ID")

mid_pc1_sample_order <- malt_pca_values %>%
  arrange(PC1) %>%
  pull(Library_ID)

ggplot(malt_pca_values, aes(PC1, PC2, color = Site_code, shape = Site_code)) +
  geom_point(size = 3) +
  theme_minimal() +
  scale_color_manual(values = Site_code_colors)

```

```{r}
mid_ordered <- full_source_results %>%
  filter(!str_detect(SampleID, outliers %>% str_c(collapse = "|"))) %>%
  filter(!str_detect(SampleID, poor_samples %>% str_c(collapse = "|"))) %>%
  filter(str_detect(SampleID, "MID")) %>%
  gather("Sources", "Percent",2:ncol(.)) %>%
  mutate(Percent = Percent * 100) %>%
  mutate(Sources = fct_relevel(Sources, "Unknown","boneARS","sediment","skin","urbanGut","ruralGut","subPlaque","supPlaque","modernCalculus"),
         SampleID = fct_relevel(SampleID, samples_order_full)) %>% # mid_pc1_sample_order
  arrange(SampleID) %>%
    ggplot(., aes(x = SampleID, y = Percent, fill = Sources)) +
         geom_bar(stat = "identity") + # , color = "black"
         theme_minimal(base_size = 14) +
         scale_fill_manual(values = full_colors) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1),
               axis.text = element_text(size = 8)) +
         # scale_y_continuous(breaks=scales::pretty_breaks(n=6)) +
         ylab("% attributed to source") +
         ggtitle("Full sources")
mid_ordered

# ggsave("~/Desktop/MID_st_ordered_plot_mid.pdf", plot = mid_ordered, device = "pdf",
#        scale = 1, width = 10, height = 5, units = c("in"), dpi = 300)

```


```{r}
full_source_results %>%
  filter(str_detect(SampleID, "MID|CMB")) %>%
  gather("Sources", "Percent",2:ncol(.)) %>%
  mutate(Sources = fct_relevel(Sources, "Unknown","boneARS","sediment","skin","urbanGut","ruralGut","subPlaque","supPlaque","modernCalculus"),
         SampleID = fct_relevel(SampleID, mid_pc1_sample_order)) %>%
  ggplot(., aes(x = SampleID, y = Percent, fill = Sources)) +
         geom_bar(stat = "identity") + # , color = "black"
         theme_minimal(base_size = 14) +
         scale_fill_manual(values = full_colors) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1),
               axis.text = element_text(size = 8)) +
         # scale_y_continuous(breaks=scales::pretty_breaks(n=6)) +
         ylab("% attributed to source") +
         ggtitle("Reduced sources")

```

















