---
title: "Smoking calcululs Figure XX1"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---


```{r load_libraries, echo = F, message = F}
library(knitr)
library(data.table)
library(janitor)
library(cuperdec)
library(compositions)
library(tidyverse)
library(cowplot)
opts_chunk$set(echo=F, warning=F, message=F, dpi=150)
```

Set the working directory of the notebook to the parent directory of the 
notebook itself.  

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("../../../"))
```

##SourceTracker

```{r load_data}

# load the taxonomy tables that have been decontaminated and the column headers are cleaned up
load("./05-results.backup/Taxonomy_tables.RData")


# load the metadata file
load("./05-results.backup/Metadata_tables.RData")

# full_metadata <- full_metadata %>%
#   mutate(`DNA_molecules_per_library_x10^6_log` = log10(`DNA_molecules_per_library_x10^6`))

outliers <- c("EXB059.A2501","LIB058.A0103","LIB058.A0106","CSS","CSD")
poor_samples <- fread("./05-results.backup/cuperdec_poor_samples.tsv") %>%
  pull(Sample)

```

```{r load_sourcetracker_out}
full_source_results <- fread("./05-results.backup/sink_predictions_full_sources_rarefied_51500.tsv")

reduced_source_results <- fread("./05-results.backup/sink_predictions_reduced_sources_rarefied_51500.tsv")

```

```{r set_colors}
full_colors <- c(modernCalculus = "#80b1d3", subPlaque = "#8dd3c7", supPlaque = "#b3de69", urbanGut = "#fccde5",  ruralGut = "#fb8072", skin = "#ffffb3", sediment = "#bebada", boneARS = "#fdb462", Unknown = "#d9d9d9")
```


Get the samples ordered by decreasing amount of modern calculus
```{r}
samples_order_full <- full_source_results %>%
  rename(Library_ID = SampleID) %>%
  full_join(., full_metadata %>%
              select(Library_ID, Site), by = "Library_ID") %>%
  mutate(Oral = modernCalculus + subPlaque + supPlaque) %>%
  arrange(Site, desc(Oral)) %>%
  pull(Library_ID)

samples_order_reduced <- reduced_source_results %>%
  rename(Library_ID = SampleID) %>%
  full_join(., full_metadata %>%
              select(Library_ID, Site), by = "Library_ID") %>%
  mutate(Oral = modernCalculus + plaque) %>%
  arrange(Site, desc(Oral)) %>%
  pull(Library_ID)

```


Plot bar charts
```{r}

st_full_plot_all <- full_source_results %>%
  filter(!str_detect(SampleID, outliers %>% str_c(collapse = "|"))) %>%
  filter(!str_detect(SampleID, poor_samples %>% str_c(collapse = "|"))) %>%
  gather("Sources", "Percent",2:ncol(.)) %>%
  mutate(Percent = Percent * 100) %>%
  mutate(Sources = fct_relevel(Sources, "Unknown","boneARS","sediment","skin","urbanGut","ruralGut","subPlaque","supPlaque","modernCalculus"),
         SampleID = fct_relevel(SampleID, samples_order_full)) %>%
  # filter(!str_detect(SampleID, "CMB")) %>%
  ggplot(., aes(x = SampleID, y = Percent, fill = Sources)) +
         geom_bar(stat = "identity") + # , color = "black"
         theme_minimal(base_size = 14) +
         scale_fill_manual(values = full_colors) +
         theme(axis.text.x = element_text(angle = 90, hjust = 1),
               axis.text = element_text(size = 8)) +
         geom_hline(yintercept=75, linetype="dotted") +
         geom_hline(yintercept=90, linetype="dotted", color = "gray50") +
         # scale_y_continuous(breaks=scales::pretty_breaks(n=6)) +
         ylab("% attributed to source") +
         ggtitle("Full sources")
st_full_plot_all

# ggsave("./06-publication/supplemental_figures/SXX6/st_full_plot_all.pdf", plot = st_full_plot_all, device = "pdf",
#        scale = 1, width = 16, height = 5, units = c("in"), dpi = 300)

# ggsave("./06-publication/supplemental_figures/SXX6/st_full_plot_all.png", plot = st_full_plot_all, device = "png",
#        scale = 1, width = 16, height = 5, units = c("in"), dpi = 300)

```


