---
title: "Smoking calcululs Supplemental Figure XX3 - batch effects"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---


```{r load_libraries, echo = F, message = F}
library(knitr)
library(mixOmics)
library(data.table)
library(vegan)
library(compositions)
library(janitor)
library(tidyverse)
library(cowplot)
```

Set the working directory of the notebook to the parent directory of the 
notebook itself.  

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("../../../"))
```

```{r metadata}
# load the metadata file
load("./05-results.backup/Metadata_tables.RData")

```

```{r load_data}
# read in the species table
mpa3_raw <- fread("./05-results.backup/mpa3_abundance_table.tsv") %>%
  select(-NCBI_tax_id)

# clean the file names
colnames(mpa3_raw) <- gsub(".metaphlan3","", colnames(mpa3_raw))
colnames(mpa3_raw) <- gsub(".SG1","", colnames(mpa3_raw))

# filter to have only species
mpa3_sp <- mpa3_raw %>% 
  filter(str_detect(clade_name, "s__")) %>%
  separate(clade_name, into = c("K","P","C","O","F","G","Species"), sep = "\\|") %>%
  select(-c("K","P","C","O","F","G")) %>%
  mutate(Species = str_replace_all(Species, "s__",""),
         Species = str_replace_all(Species, "_"," ")) %>%
  # these samples have no metadata
  select(-c("MID025.A0101","MID033.A0101","MID052.A0101","MID056.A0101","MID065.A0101","MID068.A0101","MID076.A0101","MID078.A0101")) %>%
  arrange(Species)

```


```{r}
mpa3_contaminants <- fread("./05-results.backup/contaminant_species_mid_mpa3.tsv", sep = "\t") %>%
  bind_rows(., fread("./05-results.backup/contaminant_species_kilteasheen_mpa3.tsv", sep = "\t")) %>%
  bind_rows(., fread("./05-results.backup/contaminant_species_iberia_mpa3.tsv", sep = "\t")) %>%
  unique()

# remove contaminant species from nt table
mpa3_species_decontam <- mpa3_sp %>%
  anti_join(., mpa3_contaminants)

```

```{r outliers}
outliers <- c("EXB059.A2101","EXB059.A2501","LIB058.A0103","LIB058.A0106") 
poor_samples_mpa3 <- fread("./05-results.backup/cuperdec_mpa3_poor_samples.tsv") %>%
  pull(Sample)

```

```{r}

malt_otu_pca_table <- mpa3_species_decontam %>%
  select(matches("Species|MID|CMB")) %>%
  select(-one_of(outliers)) %>%
  select(-one_of(poor_samples_mpa3)) %>%
  gather("Library_ID","Counts",2:ncol(.)) %>%
  mutate(Counts = Counts + 1) %>%
  spread(Species, Counts) %>%
  column_to_rownames("Library_ID")

# look at the screenplot to decide how many components to keep for the PCA -> will keep all but 2
mixOmics::tune.pca(malt_otu_pca_table, logratio = 'CLR')
# perform a PCA to see how the data cluster
malt_otu.pca <- mixOmics::pca(malt_otu_pca_table, ncomp = 2, logratio = 'CLR')
malt_pca_values <- malt_otu.pca$variates$X %>%
  as.data.frame() %>%
  rownames_to_column("Library_ID") %>%
  inner_join(., full_metadata, by = "Library_ID")

```

Extraction batches
```{r}
exb_batches <- ggplot(malt_pca_values, aes(PC1, PC2, color = Extraction_batch, shape = Site_code)) +
  geom_point(size = 2.5) +
  theme_minimal() +
  xlab(paste("PC1 - ", 100*(round(malt_otu.pca$prop_expl_var$X[1], 2)), "%", sep = "")) +
  ylab(paste("PC2 - ", 100*(round(malt_otu.pca$prop_expl_var$X[2], 2)), "%", sep = ""))

exb_batches

```

Library batches
```{r}

lib_batches <- ggplot(malt_pca_values, aes(PC1, PC2, color = Library_batch, shape = Site_code)) +
  geom_point(size = 2.5) +
  theme_minimal() +
  xlab(paste("PC1 - ", 100*(round(malt_otu.pca$prop_expl_var$X[1], 2)), "%", sep = "")) +
  ylab(paste("PC2 - ", 100*(round(malt_otu.pca$prop_expl_var$X[2], 2)), "%", sep = ""))

lib_batches

# ggsave("./06-publication/supplemental_figures/SXX2/st_full_plot_all.pdf", plot = st_full_plot_all, device = "pdf",
#        scale = 1, width = 16, height = 5, units = c("in"), dpi = 300)

```

```{r plot_together}

mid_batches <- plot_grid(exb_batches, lib_batches,
          nrow=2, labels = c("A", "B"), rel_widths = c(1, 1))


# ggsave("./06-publication/supplemental_figures/SXX3/mid_batches.pdf", plot = mid_batches,
#        device = "pdf", scale = 1, width = 8, height = 10, units = c("in"), dpi = 300)
# ggsave("./06-publication/supplemental_figures/SXX3/mid_batches.png", plot = mid_batches,
#        device = "png", scale = 1, width = 8, height = 10, units = c("in"), dpi = 300)

```









