---
title: "Smoking calculus Figure 5 - Streptococcus group distributions"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---


```{r load_libraries, echo = F, message = F}
library(knitr)
library(data.table)
library(janitor)
library(tidyverse)
library(cowplot)
opts_chunk$set(echo=F, warning=F, message=F, dpi=150)
```

Set the working directory of the notebook to the parent directory of the 
notebook itself.  

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("../../../"))
```

```{r strep_groups}
# read in the Strep group table James made for the Deep Evo project

strep_groups <- fread("./00-documentation.backup/dRep_strep_groups.tsv") %>%
  # remove the extrac column with the old dRep
  select(-Clade_Consensus) %>%
  # make a factor for plotting
  mutate(dRep = fct_relevel(dRep, "Sanguinis","Mitis","Salivarius","Anginosus","Bovis","Pyogenic","Mutans","Other_oral","Other","Unknown"))

```

```{r metadata}

load("./05-results.backup/Metadata_tables.RData")

```


```{r}
# set colors to resemble James' figure

clade_colors <- c("Sanguinis" = "#a50026",
                  "Mitis" = "#d73027",
                  "Salivarius" = "#f46d43",
                  "Anginosus" = "#fee090",
                  "Bovis" = "#abd9e9",
                  "Pyogenic" = "#74add1",
                  "Mutans" = "#4575b4",
                  "Oral_other" = "#313695",
                  "Other" = "#4d4d4d",
                  "Unknown" = "#e0e0e0")

genus_colors <- c("Streptococcus" = "#a50026", "Other" = "#e0e0e0")

```


## MALT RefSeq
```{r load_MALT_RefSeq_data}

# load the MALT RefSeq taxonomy tables that have been decontaminated and the column headers are cleaned up
load("./05-results.backup/Taxonomy_tables.RData")

# list poor samples from cuperdec
poor_samples_rs <- fread("./05-results.backup/cuperdec_poor_samples.tsv") %>%
  rename(Library_ID = Sample) %>%
  filter(str_detect(Library_ID, "MID")) %>%
  pull(Library_ID)

# we'll use the prevalence-filtered dataset
malt_rs <- all_species_decontam_prev %>%
  select(matches("Species|MID|CMB")) %>%
  adorn_totals(where = "col")  %>%
  filter(Total >  0) %>%
  select(-Total) %>%
  select(-poor_samples_rs)


```

First do a PCA to get the order of samples in the horseshoe
```{r pca_rs}
# prep the table

outliers <- c("EXB059.A2501","LIB058.A0103","LIB058.A0106","CSS","CSD")
poor_samples <- fread("./05-results.backup/cuperdec_poor_samples.tsv") %>%
  pull(Sample)

malt_otu_pca_table <- malt_rs %>%
  select(-one_of(outliers)) %>%
  gather("Library_ID","Counts",2:ncol(.)) %>%
  mutate(Counts = Counts + 1) %>%
  spread(Species, Counts) %>%
  column_to_rownames("Library_ID")

# perform a PCA to see how the data cluster
malt_otu.pca <- mixOmics::pca(malt_otu_pca_table, ncomp = 2, logratio = 'CLR')
malt_pca_values <- malt_otu.pca$variates$X %>%
  as.data.frame() %>%
  rownames_to_column("Library_ID") %>%
  inner_join(., full_metadata, by = "Library_ID")

mid_pc1_sample_order <- malt_pca_values %>%
  arrange(PC1) %>%
  pull(Library_ID)

ggplot(malt_pca_values, aes(PC1, PC2, color = Region, shape = Region)) +
  geom_text(aes(label = Library_ID), size = 3) +
  theme_minimal()

```


```{r malt_rs_graphs}

# set the order of samples based on proportion of Sanguinis and agninosis
# need to get the proportion of each for this
# then arrange by proportion

sample_order_rs <- malt_rs  %>%
  filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., strep_groups) %>%
  select(-Species) %>%
  select(dRep, everything()) %>%
  # long-format
  gather("Library_ID","Counts", 2:ncol(.)) %>%
  # sum together all species per group
  group_by(Library_ID, dRep) %>%
  summarize(Reads = sum(Counts)) %>%
  # transpose
  spread(dRep, Reads) %>%
  # convert table to proportions
  adorn_percentages(denominator = "row") %>%
  # arrange by Sanguinis and for the ones w/o Sanguinis, by Anginosus
  arrange(desc(Sanguinis), Anginosus)%>%
  pull(Library_ID)


strepgroups <- malt_rs %>%
  filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., strep_groups) %>%
  select(Species, dRep, everything()) %>%
  # convert to long-format
  gather("Library_ID","Counts", 3:ncol(.)) %>%
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs)) %>%
  dplyr::group_by(Library_ID, dRep) %>%
  summarize(Count_sum = sum(Counts)) %>%
  ggplot(., aes(x = Library_ID, y = Count_sum, fill = dRep)) +
         geom_bar(position = "fill", stat = "identity") + # , color = "black"
         theme_minimal(base_size = 14) +
         scale_fill_manual(values = clade_colors) +
         # theme(axis.text.x = element_blank()) +
         theme(axis.text.x = element_blank(),
               axis.text = element_text(size = 10)) +
         # scale_y_continuous(breaks=scales::pretty_breaks(n=6)) +
         # geom_hline(yintercept = 0.75, linetype = "dotted") +
         scale_y_continuous(labels = function(x) paste0(x*100)) + # Multiply by 100
         ylab("Percent") +
         labs(fill = "Group") +
         xlab("Sample")
strepgroups

```

```{r}
malt_rs %>%
  filter(str_detect(Species, "Streptococcus")) %>%
  # join with the Strep grup table for plotting
  inner_join(., strep_groups) %>%
  select(Species, dRep, everything()) %>%
  # convert to long-format
  gather("Library_ID","Counts", 3:ncol(.)) %>%
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs)) %>%
  dplyr::group_by(Library_ID, dRep) %>%
  summarize(Count_sum = sum(Counts)) %>%
  ungroup() %>%
  group_by(Library_ID) %>%
  mutate(Percent = Count_sum / sum(Count_sum)) %>%
  filter(dRep == "Anginosus" & Percent >= 0.5)

```



```{r rs_strep_proportion}

strep_prop <- malt_rs %>%
  # make a column with Strep or other
  mutate(Genus = ifelse(str_detect(Species,"Strep"),"Streptococcus","Other")) %>%
  # remove Species column leaving Genus column
  select(Genus, everything()) %>%
  select(-Species) %>%
  # convert to long format
  gather("Library_ID","Counts", 2:ncol(.)) %>%
  group_by(Library_ID, Genus) %>%
  # sum all Strep read counts and all Other read counts
  summarize(Reads = sum(Counts)) %>%
  spread(Genus, Reads) %>%
  # convert to proportions
  adorn_percentages() %>%
  ungroup()

streponly <- strep_prop %>%
  gather("Genus","Counts", 2:ncol(.)) %>%
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs)) %>%
  arrange(Library_ID) %>%
  ggplot(., aes(x = Library_ID, y = Counts, fill = Genus)) +
         geom_bar(stat = "identity") + # , color = "black"
         theme_minimal(base_size = 14) +
         scale_fill_manual(values = genus_colors) +
         theme(axis.text.x = element_blank(),
               axis.text = element_text(size = 10)) +
         scale_y_continuous(labels = function(x) paste0(x*100)) + # Multiply by 100
         ylab("Percent") +
         xlab("Sample")
streponly


```

```{r rs_strep_proportion_50}

strep_prop <- malt_rs %>%
  # make a column with Strep or other
  mutate(Genus = ifelse(str_detect(Species,"Strep"),"Streptococcus","Other")) %>%
  # remove Species column leaving Genus column
  select(Genus, everything()) %>%
  select(-Species) %>%
  # convert to long format
  gather("Library_ID","Counts", 2:ncol(.)) %>%
  group_by(Library_ID, Genus) %>%
  # sum all Strep read counts and all Other read counts
  summarize(Reads = sum(Counts)) %>%
  spread(Genus, Reads) %>%
  # convert to proportions
  adorn_percentages() %>%
  ungroup()

strep50 <- strep_prop %>%
  gather("Genus","Counts", 2:ncol(.)) %>%
  filter(Genus == "Streptococcus") %>%
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs)) %>%
  arrange(Library_ID) %>%
  ggplot(., aes(x = Library_ID, y = Counts, fill = Genus)) +
         geom_bar(stat = "identity") + # , color = "black"
         theme_minimal(base_size = 14) +
         scale_fill_manual(values = genus_colors) +
         theme(axis.text.x = element_blank(),
               axis.text = element_text(size = 10)) +
         ylim(0, 0.5) +
         # scale_y_continuous(labels = function(x) paste0(x*100)) + # Multiply by 100
         ylab("Percent") +
         xlab("Sample")
strep50


```

```{r sanguinis_anginosus}

aardvark <- malt_rs %>%
  # make a column with Strep or other
  mutate(Genus_inc = ifelse(str_detect(Species,"Streptococcus"),"Streptococcus", "NonStrep")) %>%
  left_join(., strep_groups , by = "Species") %>%
  # remove Species column leaving Genus column
  mutate(Genus = replace_na(as.character(dRep), "NonStrep")) %>%
  select(Genus, everything()) %>%
  select(-matches("Species|dRep|Genus_inc")) %>%
  # convert to long format
  gather("Library_ID","Counts", 2:ncol(.)) %>%
  group_by(Library_ID, Genus) %>%
  # sum all Strep read counts and all Other read counts
  summarize(Reads = sum(Counts)) %>%
  spread(Genus, Reads) %>%
  # convert to proportions
  adorn_percentages() %>%
  ungroup() %>%
  # rearrange column order
  select(Library_ID, NonStrep, Sanguinis, Anginosus, everything()) %>%
  # now sum counts for columns we're not interested in 
  mutate(OtherStrep = select(., Bovis:Salivarius) %>% rowSums()) %>%
  # rearrange column order again and drop the unwanted columns
  select(Library_ID, NonStrep, Sanguinis, Anginosus, OtherStrep) %>%
  pivot_longer(!Library_ID, names_to = "Genus", values_to = "Counts") %>%
  # order the Library ID by 
  mutate(Library_ID = fct_relevel(Library_ID, sample_order_rs),
         Counts = Counts + 0.0001) %>%
         # Genus = fct_relevel(Genus, "NonStrep","OtherStrep","Sanguinis","Anginosus")) %>%
  filter(str_detect(Genus, "Sanguinis|Anginosus")) 

aardvark_plot <- aardvark%>%
  arrange(Library_ID) %>%
  # filter(Counts != 0) %>%
  mutate(Library_ID = fct_drop(Library_ID)) %>%
  ggplot(., aes(x = Library_ID, y = Counts, shape = Genus, bg = Genus)) +
         geom_point(size = 2, color = "grey50") + # , color = "black"
         theme_minimal(base_size = 14) +
         scale_fill_manual(values = c("#fee090","#a50026")) +
         scale_shape_manual(values = c(21,24)) +
         theme(axis.text.x = element_blank(),
               axis.text = element_text(size = 10)) +
         scale_y_log10() +
         ylab("Percent") +
         ggtitle("")

aardvark_plot

```

```{r plot_together}

strep_groups <- plot_grid(strepgroups, streponly, aardvark_plot,
          nrow=3, labels = c("A", "B", "C"), rel_widths = c(1, 1))

strep_groups

ggsave("./06-publication/main_figures/Figure_5/strep_groups.pdf", plot = strep_groups,
       device = "pdf", scale = 1, width = 8, height = 7, units = c("in"), dpi = 300)
# ggsave("./06-publication/main_figures/Figure_5/strep_groups.png", plot = strep_groups,
#        device = "png", scale = 1, width = 8, height = 7, units = c("in"), dpi = 300)

```



