---
title: "Smoking calculus metadata graphs"
author: "Irina Velsko"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output:
    github_document:
        fig_width: 8
        fig_height: 6
        toc: true
---

```{r load_libraries, echo = F, message = F}
library(knitr)
library(data.table)
library(microshades)
library(tidyverse)
library(patchwork)

```

```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("../../../"))
```

## Country  map
```{r}
library("ggplot2")
theme_set(theme_bw())
library("sf")
library("rnaturalearth")
library("rnaturalearthdata")
library("rgeos")
library("maps")
library("dplyr")
```

# Site map
```{r}
# pull country data
world <- ne_countries(scale = "medium", returnclass = "sf")

# add coordinates to a dataframe
smoking_sites <- data.frame(longitude = c(4.9168030, -2.9804059,-1.257,-3.7892050,-0.3765000), latitude = c(52.5519900, 43.2805735,51.752,37.7769480,39.4695270), Site = c("MID","CMB","Radcliffe","JAE","VLC"), Data = c("New","New","Published","Published","Published"))

non_smoking_sites <- data.frame(longitude = c(-8.2023080,-0.8088890,-2.8622220), latitude = c(54.0068400,38.2486110,38.6963890), Site = c("Kilteasheen","ELR","IVE"), Data = c("Published","New","New"))


# plot the map
sampling_sites_europe <- ggplot(data = world) +
  geom_sf(colour = "#ffffff", fill = "#bbbbbb", linetype = "dotted") +
  #for grey map with white lines
  geom_sf(fill = "#f7fcf5") +
  geom_point(data = non_smoking_sites, aes(x = longitude, y = latitude, color = Data), size = 4,
        shape = 17) +
  geom_point(data = smoking_sites, aes(x = longitude, y = latitude, color = Data), size = 4,
        shape = 19) +
  coord_sf(xlim = c(-12, 20), ylim = c(35, 60), expand = FALSE) +
  theme_void() +
  scale_color_manual(values = c("black","grey50"))
sampling_sites_europe

ggsave("./06-publication/main_figures/Figure_1/sample_site_map.pdf", plot = sampling_sites_europe, device = "pdf",
       scale = 1, width = 5, height = 5, units = c("in"), dpi = 300)

```


## Osteological metadata
```{r load_metadata}

load("./05-results.backup/Metadata_tables.RData")
```


```{r smoking_pd}

smpd <- full_metadata %>%
  filter(str_detect(Library_ID, "MID")) %>%
  drop_na(Pipenotch) %>%
  # filter(Age != "13-18") %>%
  ggplot(., aes(x = Pipenotch, y = Age, fill = Peridontal_affect_score, shape = Sex, size = `%AMTL`)) +
    ggpointgrid::geom_pointrect(scale_x = 0.10, scale_y = 0.22, color = "black", stroke = 0.5) +
    theme_minimal(base_size = 14) +
    scale_size_continuous(range = c(3,10)) +
    scale_shape_manual(values = c(21, 23, 22)) +
    scale_fill_gradient(low = "blue", high = "red") +
    # scale_color_manual(values = microshades_palette("micro_green")) +
    theme(axis.text = element_text(size = 14)) +
    xlab("Pipe notch(es)") +
    ylab("Age group")
smpd

# ggsave("./06-publication/main_figures/Figure_1/smpd.pdf", plot = smpd, device = "pdf",
#        scale = 1, width = 8, height = 5, units = c("in"), dpi = 300)

```

```{r smoking_caries}
smc <- full_metadata %>%
  filter(str_detect(Library_ID, "MID")) %>%
  # filter(Age != "13-18") %>%
  drop_na(Pipenotch) %>%
  ggplot(., aes(x = Pipenotch, y = Age, fill = `%teeth_with_caries`, shape = Sex, size = `%AMTL`)) +
    ggpointgrid::geom_pointrect(scale_x = 0.10, scale_y = 0.22, color = "black", stroke = 0.5) +
    theme_minimal(base_size = 14) +
    scale_size_continuous(range = c(3,10)) +
    scale_shape_manual(values = c(21, 23, 22)) +
    scale_fill_gradient(low = "blue", high = "red") +
    theme(axis.text = element_text(size = 14)) +
    xlab("Pipe notch(es)") +
    ylab("Age group")
smc

# ggsave("./06-publication/main_figures/Figure_1/smc.pdf", plot = smc, device = "pdf",
#        scale = 1, width = 10, height = 7, units = c("in"), dpi = 300)

```

```{r smoking_calc_score}
smcs <- full_metadata %>%
  filter(str_detect(Library_ID, "MID")) %>%
  # filter(Age != "13-18") %>%
  drop_na(Pipenotch) %>%
  ggplot(., aes(x = Pipenotch, y = Age, fill = Calc_sub_SI_score, shape = Sex, size = `%AMTL`)) +
    ggpointgrid::geom_pointrect(scale_x = 0.10, scale_y = 0.22, color = "black", stroke = 0.5) +
    theme_minimal(base_size = 14) +
    scale_size_continuous(range = c(3,10)) +
    scale_shape_manual(values = c(21, 23, 22)) +
    scale_fill_gradient(low = "blue", high = "red") +
    theme(axis.text = element_text(size = 14)) +
    xlab("Pipe notch(es)") +
    ylab("Age group")
smcs

# ggsave("./06-publication/main_figures/Figure_1/smcs.pdf", plot = smcs, device = "pdf",
#        scale = 1, width = 8, height = 5, units = c("in"), dpi = 300)

```

```{r plot_together}
metaplot <- smpd + smcs
metaplot

ggsave("./06-publication/main_figures/Figure_1/metaplot.pdf", plot = metaplot,
       device = "pdf", scale = 1, width = 21, height = 8, units = c("in"), dpi = 300)

```












